services:
  k6-load-test:
    image: grafana/k6:0.48.0
    deploy:
      resources:
        limits:
          memory: 512Mb
          cpus: "1"
    volumes:
      - ./scripts:/app
    networks:
      - k6-net
    command: [ "run", "/app/items/load-test.js" ]  

networks:
  k6-net:
