name: Checks

on:
  workflow_call:
    inputs:
      node-version:
        default: 20.x
        required: false
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Linting
        run: npm run lint
