name: Checks

on:
  workflow_call:

jobs:
  checks:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: npm
    - name: Install Dependencies
      run: npm ci
    - name: Run Linter
      run: npm run lint
