name: Dependency Review
on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - "**/*.md"
    - docs/**

jobs:
  dependency-review:
    name: Dependencies Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        show-progress: false
    - name: Dependency Review
      uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
      with:
        fail-on-scope: runtime,unknown
        comment-summary-in-pr: on-failure
