name: 'Performance Test'

on:
  workflow_call:
    inputs:
      node-version:
        default: 20.x
        required: false
        type: string
  # TODO: Update this when we're ready to go - it should happen at every tag or something
  push:
    branches:
      - 'feat/perf-test'


jobs:
  k6_ci_test:
      name: k6 CI Test run
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: start MongoDB and CRUD Service via docker file
          run: docker compose up --file bench/docker-compose.yml up -d --force-recreate

        - name: Run k6 test
          uses: grafana/k6-action@v0.3.1
          with:
              filename: bench/scripts/items/load-test.js
