name: 'Performance Test'

on:
  workflow_call:
    inputs:
      node-version:
        default: 20.x
        required: false
        type: string
  # TODO: Update this when we're ready to go - it should happen at every tag or something
  push:
    branches:
      - 'feat/perf-test'


jobs:
  k6_ci_test:
      name: k6 CI Test run
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # - name: start MongoDB and CRUD Service via docker file
        #   run: docker compose --file bench/docker-compose.yml up -d --force-recreate

        - name: start MongoDB instance
          uses: supercharge/mongodb-github-action@v1.10.0
          with:
            mongodb-version: "6.0"
            mongodb-db: bench-test

        - name: Populate Customer collection and Registered Customer View
          run: cd bench/data && npm i && node generate-customer-data.js -c mongodb://localhost:27017/bench-test -d bench-test -n 100000 -s 250

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: npm
  
        - name: Install
          run: npm ci

        - name: 'Start CRUD Service instance'
          run: (npm run start&)
          env:
            LOG_LEVEL: info
            COLLECTION_DEFINITION_FOLDER: /home/runner/work/crud-service/crud-service/bench/collections
            VIEWS_DEFINITION_FOLDER: /home/runner/work/crud-service/crud-service/bench/views
            USER_ID_HEADER_KEY: userid
            CRUD_LIMIT_CONSTRAINT_ENABLED: true
            CRUD_MAX_LIMIT: 200
            MONGODB_URL: mongodb://localhost:27017/bench-test

        - name: Run k6 load test (collection Item)
          uses: grafana/k6-action@v0.3.1
          with:
              filename: bench/scripts/items/load-test.js
              # flags: --out json=load-test-results.json

        - name: Run k6 spike test (collection Customers)
          uses: grafana/k6-action@v0.3.1
          with:
              filename: bench/scripts/customers/spike-test.js
              # flags: --out json=spike-test-results.json

        - name: Run k6 stress test (view Registered Customers)
          uses: grafana/k6-action@v0.3.1
          with:
              filename: bench/scripts/registered-customers/stress-test.js
              # flags: --out json=stress-test-results.json

        # - name: Upload performance test results
        #   uses: actions/upload-artifact@v3
        #   with:
        #     name: load-test-report
        #     path: load-test-results.json

        
