name: Docker container security check

on:
  workflow_call:
    inputs:
      checksum:
        required: false
        type: string
      version:
        required: true
        type: string
    secrets:
      security_checks_token:
        required: true
        
jobs:
  security-checks:
    name: Triggers security checks
    runs-on: ubuntu-latest

    steps:
      - name: Invoke API
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: |
          curl --request POST \
            --form token=${{ secrets.security_checks_token }} \
            --form ref=main \
            --form "variables[VERSION]=${{ inputs.version }}" \
            --form "variables[CHECKSUM]=${{ inputs.checksum }}" \
            "https://git.tools.mia-platform.eu/api/v4/projects/86291/trigger/pipeline"
