name: Tag CI

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    needs:
      - tests
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/release-docker.yml
    with:
      push: true
    secrets:
      docker_username: ${{ secrets.BOT_DOCKER_USERNAME }}
      docker_token: ${{ secrets.BOT_DOCKER_TOKEN }}
      github_cr_token: ${{ secrets.GITHUB_TOKEN }}
      security_checks_token: ${{ secrets.CRUD_SERVICE_SYSDIG_CHECK_TRIGGER }}
      nexus_username: ${{ secrets.NEXUS_USER }}
      nexus_token: ${{ secrets.NEXUS_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs:
      - release-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-rc.') }}
